//package org.example.domain;
//
//public record PdfRequest(
//        String actionType,
//        String readingMethod,
//        String address,
//        String date,
//        String energyBefore,
//        String waterBefore,
//        String flowConverterBefore,
//        String meterDismantled,
//        String meterDismantledSerialNumber,
//        String meterDismantledProductionYear,
//        String meterDismantledRadioAddress,
//        String meterDismantledImpulse,
//        String meterDismantledLegalizationYear,
//        String meterDismantledLegalizationMonth,
//        String meterInstalled,
//        String meterInstalledSerialNumber,
//        String meterInstalledProductionYear,
//        String meterInstalledRadioAddress,
//        String meterInstalledImpulse,
//        String meterInstalledLegalizationYear,
//        String meterInstalledLegalizationMonth,
//        String flowMeterDismantled,
//        String flowMeterDismantledSerialNumber,
//        String flowMeterDismantledProductionYear,
//        String flowMeterDismantledQN,
//        String flowMeterDismantledDN,
//        String flowMeterDismantledImpulse,
//        String flowMeterDismantledLegalizationYear,
//        String flowMeterDismantledLegalizationMonth,
//        String flowMeterInstalled,
//        String flowMeterInstalledSerialNumber,
//        String flowMeterInstalledProductionYear,
//        String flowMeterInstalledQN,
//        String flowMeterInstalledDN,
//        String flowMeterInstalledImpulse,
//        String flowMeterInstalledLegalizationYear,
//        String flowMeterInstalledLegalizationMonth,
//        String tempSensorDismantledPT,
//        String tempSensorDismantledType,
//        String tempSensorDismantledSerialNumber1,
//        String tempSensorDismantledSerialNumber2,
//        String tempSensorDismantledProductionYear,
//        String tempSensorDismantledLegalizationYear,
//        String tempSensorDismantledLegalizationMonth,
//        String tempSensorInstalledPT,
//        String tempSensorInstalledType,
//        String tempSensorInstalledSerialNumber1,
//        String tempSensorInstalledSerialNumber2,
//        String tempSensorInstalledProductionYear,
//        String tempSensorInstalledLegalizationYear,
//        String tempSensorInstalledLegalizationMonth,
//        String otherActionsService,
//        String energyAfter,
//        String waterAfter,
//        String flowConverterAfter
//) {
//}
//
//
//
