package org.example;

public record PdfRequest(
        String actionType1,
        String actionType2,
        String address,
        String date,
        String energyBefore,
        String waterBefore,
        String flowConverterBefore,
        String meterDismantled,
        String meterDismantledSerialNumber,
        String meterDismantledProductionYear,
        String meterDismantledRadioAddress,
        String meterDismantledImpulse,
        String meterInstalled,
        String meterInstalledSerialNumber,
        String meterInstalledProductionYear,
        String meterInstalledRadioAddress,
        String meterInstalledImpulse,
        String meterInstalledLegalizationDate1,
        String meterInstalledLegalizationDate2,
        String flowMeterDismantled,
        String flowMeterDismantledSerialNumber,
        String flowMeterDismantledProductionYear,
        String flowMeterDismantledQN,
        String flowMeterDismantledDN,
        String flowMeterDismantledImpulse,
        String flowMeterInstalled,
        String flowMeterInstalledSerialNumber,
        String flowMeterInstalledProductionYear,
        String flowMeterInstalledQN,
        String flowMeterInstalledDN,
        String flowMeterInstalledImpulse,
        String flowMeterInstalledLegalizationDate1,
        String flowMeterInstalledLegalizationDate2,
        String tempSensorDismantledPT,
        String tempSensorDismantledType,
        String tempSensorDismantledSerialNumber1,
        String tempSensorDismantledSerialNumber2,
        String tempSensorDismantledProductionYear,
        String tempSensorInstalledPT,
        String tempSensorInstalledType,
        String tempSensorInstalledSerialNumber1,
        String tempSensorInstalledSerialNumber2,
        String tempSensorInstalledProductionYear,
        String tempSensorInstalledLegalizationDate1,
        String tempSensorInstalledLegalizationDate2,
        String otherActionsService,
        String energyAfter,
        String waterAfter,
        String flowConverterAfter
) {
}



