pdf:
  fontPath: ./backend/src/main/resources/ttf/DejaVuSans-Bold.ttf
  readPath: ./backend/src/main/resources/static/
  savePath: ./backend/src/main/resources/static/generatedpdfs/
  existingGeneratedPdfFilesPath: ./backend/src/main/resources/static/generatedpdfs/
  language: pl
#  language: eng

#pdf:
#  fontPath: /home/ec2-user/static/ttf/DejaVuSans-Bold.ttf
#  readPath: /home/ec2-user/static/
#  savePath: /home/ec2-user/static/generatedpdfs/
#  existingGeneratedPdfFilesPath: /home/ec2-user/static/generatedpdfs/
#  language: pl
###  language: eng